autoscaling:
  enabled: true
  maxReplicas: 5
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
database:
  databaseName: casdoor
  driver: postgres
  host: postgres
  password: casdoor
  port: "5432"
  sslMode: disable
  user: casdoor